# Generated by Django 6.0.1 on 2026-01-26 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_file', models.FileField(upload_to='models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pkl', 'h5', 'pt', 'joblib', 'pth', 'onnx'])])),
                ('parameters', models.JSONField(blank=True, default=dict, null=True)),
                ('version', models.IntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
