# Generated by Django 6.0.1 on 2026-01-27 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_tracking_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlmodels',
            old_name='name',
            new_name='model_name',
        ),
    ]
