# Generated by Django 6.0.1 on 2026-01-27 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset_tracking_api', '0004_alter_datasets_hash'),
        ('model_tracking_api', '0002_rename_name_mlmodels_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_used', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset_tracking_api.datasets')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_tracking_api.mlmodels')),
            ],
        ),
    ]
